# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68c4706dfefcb23bd5b6a7a5f2099fd22660e32ccd10ea8446d5f74bbba8f33609a7e0f0a669f9ff7f0082c0e10e20e5d27fd7ecfd0ef5e203aa1d38f7886493

test:
  secret_key_base: ad48ce41ca852d436f85d65104e3d63afff6bab110051271ad3d90dd011738b19bda94a9f23e85a6311600e049c4f263553d9cdbdb11410c8dd6bdf5b14eaa8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
